<?php
/**
 * Brands index placeholder data — mirrors /docs/design/brands.js.
 *
 * Used by templates/brands-placeholder.php while there are no real
 * `product_brand` terms to read from. Replace with `get_terms()` once
 * the brand taxonomy is populated.
 *
 * Each row: name, type (Niche|Designer|Indie), origin, count, isNew, style.
 *
 * @package Lenvy
 */

defined('ABSPATH') || exit();

return [
	['name' => 'Acqua di Parma',           'type' => 'Designer', 'origin' => 'Parma, IT',     'count' => 18, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Aesop',                    'type' => 'Niche',    'origin' => 'Melbourne',     'count' => 12, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Amouage',                  'type' => 'Niche',    'origin' => 'Muscat, OM',    'count' => 24, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Annick Goutal',            'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' =>  9, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Atelier Cologne',          'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 14, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Bond No. 9',               'type' => 'Niche',    'origin' => 'New York, US',  'count' => 16, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Boucheron',                'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' =>  7, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Bvlgari',                  'type' => 'Designer', 'origin' => 'Rome, IT',      'count' => 22, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Byredo',                   'type' => 'Niche',    'origin' => 'Stockholm, SE', 'count' => 28, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Carolina Herrera',         'type' => 'Designer', 'origin' => 'Madrid, ES',    'count' => 11, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Cartier',                  'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' =>  9, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Chanel',                   'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 26, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Chloé',                    'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' =>  8, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Clive Christian',          'type' => 'Niche',    'origin' => 'Londen, UK',    'count' => 14, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Comme des Garçons',        'type' => 'Niche',    'origin' => 'Tokio, JP',     'count' => 19, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Creed',                    'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 32, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Diptyque',                 'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 24, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Dior',                     'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 38, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Dolce & Gabbana',          'type' => 'Designer', 'origin' => 'Milaan, IT',    'count' => 14, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Editions de Parfums',      'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 16, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Elie Saab',                'type' => 'Designer', 'origin' => 'Beiroet, LB',   'count' =>  6, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Escentric Molecules',      'type' => 'Niche',    'origin' => 'Berlijn, DE',   'count' =>  8, 'isNew' => false, 'style' => 'mono'],
	['name' => "Etat Libre d'Orange",      'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 18, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Floraïku',                 'type' => 'Niche',    'origin' => 'Tokio, JP',     'count' => 10, 'isNew' => true,  'style' => 'italic'],
	['name' => 'Frederic Malle',           'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 22, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Giorgio Armani',           'type' => 'Designer', 'origin' => 'Milaan, IT',    'count' => 18, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Givenchy',                 'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 12, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Goldfield & Banks',        'type' => 'Niche',    'origin' => 'Sydney, AU',    'count' =>  9, 'isNew' => true,  'style' => 'thin'],
	['name' => 'Guerlain',                 'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 28, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Gucci',                    'type' => 'Designer', 'origin' => 'Florence, IT',  'count' => 16, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Hermès',                   'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 22, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Histoires de Parfums',     'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 14, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Initio Parfums',           'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 11, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Issey Miyake',             'type' => 'Designer', 'origin' => 'Tokio, JP',     'count' =>  8, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Jean Paul Gaultier',       'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 13, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Jo Malone',                'type' => 'Niche',    'origin' => 'Londen, UK',    'count' => 26, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Juliette Has a Gun',       'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 12, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Jusbox',                   'type' => 'Niche',    'origin' => 'Milaan, IT',    'count' =>  9, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Kenzo',                    'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' =>  7, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Kilian Paris',             'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 18, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Lalique',                  'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' =>  8, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Lancôme',                  'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 10, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Lattafa',                  'type' => 'Niche',    'origin' => 'Sharjah, AE',   'count' => 20, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Le Labo',                  'type' => 'Niche',    'origin' => 'New York, US',  'count' => 22, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Maison Crivelli',          'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' =>  8, 'isNew' => true,  'style' => 'thin'],
	['name' => 'Maison Francis Kurkdjian', 'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 20, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Maison Margiela',          'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 16, 'isNew' => false, 'style' => 'mono'],
	['name' => 'Maison Verdier',           'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 12, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Mancera',                  'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 14, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Memo Paris',               'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 16, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Montale',                  'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 18, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Mugler',                   'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 11, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Narciso Rodriguez',        'type' => 'Designer', 'origin' => 'Newark, US',    'count' =>  9, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Nasomatto',                'type' => 'Niche',    'origin' => 'Amsterdam, NL', 'count' =>  7, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Nishane',                  'type' => 'Niche',    'origin' => 'Istanbul, TR',  'count' => 18, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Olfactive Studio',         'type' => 'Niche',    'origin' => 'Parijs, FR',    'count' => 11, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Ormonde Jayne',            'type' => 'Niche',    'origin' => 'Londen, UK',    'count' => 14, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Orto Parisi',              'type' => 'Niche',    'origin' => 'Milaan, IT',    'count' =>  7, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Paco Rabanne',             'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 14, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Parfums de Marly',         'type' => 'Niche',    'origin' => 'Versailles, FR','count' => 24, 'isNew' => false, 'style' => 'italic'],
	['name' => "Penhaligon's",             'type' => 'Niche',    'origin' => 'Londen, UK',    'count' => 22, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Prada',                    'type' => 'Designer', 'origin' => 'Milaan, IT',    'count' => 11, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Roja Parfums',             'type' => 'Niche',    'origin' => 'Londen, UK',    'count' => 18, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Rochas',                   'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' =>  6, 'isNew' => false, 'style' => 'caps-thin'],
	['name' => 'Salvatore Ferragamo',      'type' => 'Designer', 'origin' => 'Florence, IT',  'count' =>  9, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Serge Lutens',             'type' => 'Niche',    'origin' => 'Marrakech, MA', 'count' => 22, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Sospiro',                  'type' => 'Niche',    'origin' => 'Modena, IT',    'count' => 10, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Thierry Mugler',           'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' =>  8, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Tiziana Terenzi',          'type' => 'Niche',    'origin' => 'Modena, IT',    'count' => 16, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Tom Ford',                 'type' => 'Designer', 'origin' => 'New York, US',  'count' => 28, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Valentino',                'type' => 'Designer', 'origin' => 'Rome, IT',      'count' => 10, 'isNew' => false, 'style' => 'serif'],
	['name' => 'Versace',                  'type' => 'Designer', 'origin' => 'Milaan, IT',    'count' => 13, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Vilhelm Parfumerie',       'type' => 'Niche',    'origin' => 'New York, US',  'count' =>  9, 'isNew' => false, 'style' => 'thin'],
	['name' => 'Viktor & Rolf',            'type' => 'Designer', 'origin' => 'Amsterdam, NL', 'count' => 11, 'isNew' => false, 'style' => 'caps'],
	['name' => 'Xerjoff',                  'type' => 'Niche',    'origin' => 'Turijn, IT',    'count' => 26, 'isNew' => false, 'style' => 'italic'],
	['name' => 'Yves Saint Laurent',       'type' => 'Designer', 'origin' => 'Parijs, FR',    'count' => 22, 'isNew' => false, 'style' => 'caps-bold'],
	['name' => 'Zaharoff',                 'type' => 'Indie',    'origin' => 'Athene, GR',    'count' =>  4, 'isNew' => true,  'style' => 'caps-thin'],
	['name' => 'Zoologist',                'type' => 'Indie',    'origin' => 'Toronto, CA',   'count' =>  6, 'isNew' => false, 'style' => 'thin'],
];
